openapi: 3.0.3
info:
  title: Action (Matter) Bill Settings Action Bill Settings Participant Additional Notification Methods API
  description: For retrieving Action Bill Settings. For historical reasons Matters are referred to as *actions* in this version of the API. For information of how to construct requests utilising fieldsets, sorting, paging, filters, and '*includes*', please refer to the API Developer Portal. E&OE.
  version: '1.0'
tags:
- name: Participant Additional Notification Methods
paths:
  /participantadditionalnotificationmethods:
    get:
      description: Returns a list of all Participant Additional Notification Methods.
      tags:
      - Participant Additional Notification Methods
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/participantadditionalnotificationmethods'
    post:
      description: Create a new Participant Additional Notification Method.
      tags:
      - Participant Additional Notification Methods
      requestBody:
        $ref: '#/components/requestBodies/CreateParticipantAdditionalNotificationMethod'
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantAdditionalNotificationMethod'
  /participantadditionalnotificationmethods/{id}:
    get:
      description: Returns a single Participant Additional Notification Method.
      tags:
      - Participant Additional Notification Methods
      parameters:
      - name: id
        in: path
        description: Unique identifier for the Participant Additional Notification Method.
        required: true
        schema:
          type: string
        example: 5410
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantAdditionalNotificationMethod'
    put:
      description: Updates a single Participant Additional Notification Method record.
      tags:
      - Participant Additional Notification Methods
      parameters:
      - name: id
        in: path
        description: Unique identifier for a single Participant Additional Notification Method record.
        required: true
        schema:
          type: integer
          format: integer
        example: 1176
      requestBody:
        $ref: '#/components/requestBodies/UpdateParticipantAdditionalNotificationMethod'
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantAdditionalNotificationMethod'
    delete:
      description: Delete a single Participant Additional Notification Method record.
      tags:
      - Participant Additional Notification Methods
      parameters:
      - name: id
        in: path
        description: Unique identifier for the Participant Additional Notification Method record.
        required: true
        schema:
          type: string
        example: 5410
      responses:
        '204':
          description: Success, No content.
components:
  schemas:
    participantadditionalnotificationmethods:
      type: object
      properties:
        participantadditionalnotificationmethods:
          type: array
          items:
            $ref: '#/components/schemas/ParticipantAdditionalNotificationMethod'
        meta:
          $ref: '#/components/schemas/PageMetaData'
    PagingData:
      type: object
      properties:
        participantadditionalnotificationmethods:
          $ref: '#/components/schemas/ParticipantAdditionalNotificationMethodPageData'
    ParticipantAdditionalNotificationMethodPageData:
      type: object
      properties:
        recordCount:
          description: The total number of Participant Additional Notification Methods returned by the underlying query.
          type: integer
          example: 4
        pageCount:
          description: The total number of pages generated by the underlying query.
          type: integer
          example: 8
        page:
          description: The page number for this page of Participant Additional Notification Methods.
          type: integer
          example: 2
        pageSize:
          description: Page size.
          type: integer
          example: 50
        prevPage:
          description: A URL to the previous page of Participant Additional Notification Methods.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/participantadditionalnotificationmethods?page=1
        nextPage:
          description: A URL to the next page of Participant Additional Notification Methods.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/participantadditionalnotificationmethods?page=3
    CreateParticipantAdditionalNotificationMethod:
      type: object
      required:
      - notificationMethod
      - address
      properties:
        notificationMethod:
          description: The method of notification.
          enum:
          - E-Mail
          - SMS
          - Phone
          - Fax
          - Mail
          - Skype
          - Facebook
          - IM
          - Twitter
          type: string
          format: string
          example: Facebook
        address:
          description: The address applicable to the notification method.
          type: string
          format: string
          example: john.smith@mycompany.com
        notes:
          description: Optional notes for this notification method.
          type: string
          format: string
          example: Phone number of secondary property.
        links:
          $ref: '#/components/schemas/CreateParticipantAdditionalNotificationMethodLinks'
    UpdateParticipantAdditionalNotificationMethodLinks:
      type: object
      required:
      - participant
      properties:
        participant:
          description: Unique identifier of the participant to whom this additional notification method is to be associated.
          example: 8945
          type: integer
    UpdateParticipantAdditionalNotificationMethod:
      type: object
      required:
      - notificationMethod
      - address
      properties:
        notificationMethod:
          description: The method of notification.
          enum:
          - E-Mail
          - SMS
          - Phone
          - Fax
          - Mail
          - Skype
          - Facebook
          - IM
          - Twitter
          type: string
          format: string
          example: Facebook
        address:
          description: The address applicable to the notification method.
          type: string
          format: string
          example: john.smith@mycompany.com
        notes:
          description: Optional notes for this notification method.
          type: string
          format: string
          example: Phone number of secondary property.
        links:
          $ref: '#/components/schemas/UpdateParticipantAdditionalNotificationMethodLinks'
    CreateParticipantAdditionalNotificationMethodLinks:
      type: object
      required:
      - participant
      properties:
        participant:
          description: Unique identifier of the participant to whom this additional notification method is to be associated.
          example: 8945
          type: integer
    PageMetaData:
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingData'
    ParticipantAdditionalNotificationMethodLinks:
      type: object
      properties:
        participant:
          description: Unique identifier of the participant to whom this additional notification method is to be associated.
          example: 8945
          type: integer
    ParticipantAdditionalNotificationMethod:
      type: object
      properties:
        notificationMethod:
          description: The method of notification.
          enum:
          - E-Mail
          - SMS
          - Phone
          - Fax
          - Mail
          - Skype
          - Facebook
          - IM
          - Twitter
          type: string
          format: string
          example: Facebook
        address:
          description: The address applicable to the notification method.
          type: string
          format: string
          example: john.smith@mycompany.com
        notes:
          description: Optional notes for this notification method.
          type: string
          format: string
          example: Phone number of secondary property.
        links:
          $ref: '#/components/schemas/ParticipantAdditionalNotificationMethodLinks'
  requestBodies:
    UpdateParticipantAdditionalNotificationMethod:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateParticipantAdditionalNotificationMethod'
    CreateParticipantAdditionalNotificationMethod:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateParticipantAdditionalNotificationMethod'
externalDocs:
  description: API Developer Portal - Constructing API Requests
  url: https://docs.actionstep.com/api-requests/
