openapi: 3.0.3
info:
  title: Action (Matter) Bill Settings Action Bill Settings Participant Default Types API
  description: For retrieving Action Bill Settings. For historical reasons Matters are referred to as *actions* in this version of the API. For information of how to construct requests utilising fieldsets, sorting, paging, filters, and '*includes*', please refer to the API Developer Portal. E&OE.
  version: '1.0'
tags:
- name: Participant Default Types
paths:
  /participantdefaulttypes:
    get:
      description: Returns a list of participant default types for each Contact.
      tags:
      - Participant Default Types
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedParticipantDefaultTypes'
    post:
      description: Add an existing participant default type to an existing Contact.
      tags:
      - Participant Default Types
      requestBody:
        $ref: '#/components/requestBodies/AddParticipantDefaultType'
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantDefaultType'
  /participantdefaulttypes/{id}:
    delete:
      description: Removes a participant default type from a Contact.
      tags:
      - Participant Default Types
      parameters:
      - name: id
        in: path
        description: Unique identifier for a participant default type. The identifier is a composite value composed from the participant (contact) identifier and the participant type identifier, separated by "--".
        required: true
        schema:
          type: string
        example: 1024--31
      responses:
        '204':
          description: Success, No content.
components:
  schemas:
    CreateParticipantDefaultTypeLinksLink:
      type: object
      properties:
        participantType:
          description: Unique identifier of the participant type.
          example: 31
          type: integer
        participant:
          description: Unique identifier of the participant.
          example: 1024
          type: integer
    CreateParticipantDefaultType:
      type: object
      properties:
        participantdefaulttypes:
          $ref: '#/components/schemas/CreateParticipantDefaultTypeLinks'
    CreateParticipantDefaultTypeLinks:
      type: object
      properties:
        links:
          $ref: '#/components/schemas/CreateParticipantDefaultTypeLinksLink'
    ParticipantDefaultTypeLinks:
      type: object
      properties:
        participantType:
          description: Unique identifier of the participant type.
          example: 31
          type: integer
        participant:
          description: Unique identifier of the participant.
          example: 1024
          type: integer
    PagingData:
      type: object
      properties:
        participantdefaulttypes:
          $ref: '#/components/schemas/ParticipantDefaultTypesPageData'
    ParticipantDefaultTypesPageData:
      type: object
      properties:
        recordCount:
          description: The total number of participant default types returned by the underlying query.
          type: integer
          example: 23
        pageCount:
          description: The total number of pages generated by the underlying query.
          type: integer
          example: 47
        page:
          description: The page number for this page of participant default types.
          type: integer
          example: 2
        pageSize:
          description: Page size.
          type: integer
          example: 50
        prevPage:
          description: A URL to the previous page of participant default types.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/participantdefaulttypes?page=1
        nextPage:
          description: A URL to the next page of participant default types.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/participantdefaulttypes?page=3
    PagedParticipantDefaultTypes:
      type: object
      properties:
        participantdefaulttypes:
          type: array
          items:
            $ref: '#/components/schemas/ParticipantDefaultType'
        meta:
          $ref: '#/components/schemas/PageMetaData'
    PageMetaData:
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingData'
    ParticipantDefaultType:
      type: object
      properties:
        id:
          description: Unique identifier for a participant default type. The identifier is a composite value composed from the participant identifier and the participant type identifier, separated by "--".
          example: 1024--31
          type: string
        links:
          $ref: '#/components/schemas/ParticipantDefaultTypeLinks'
  requestBodies:
    AddParticipantDefaultType:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateParticipantDefaultType'
externalDocs:
  description: API Developer Portal - Constructing API Requests
  url: https://docs.actionstep.com/api-requests/
