openapi: 3.0.3
info:
  title: Action (Matter) Bill Settings Action Bill Settings Primary Language API
  description: For retrieving Action Bill Settings. For historical reasons Matters are referred to as *actions* in this version of the API. For information of how to construct requests utilising fieldsets, sorting, paging, filters, and '*includes*', please refer to the API Developer Portal. E&OE.
  version: '1.0'
tags:
- name: Primary Language
paths:
  /primarylanguage:
    get:
      description: Returns the list of available primary languages.
      tags:
      - Primary Language
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedPrimaryLanguage'
components:
  schemas:
    PrimaryLanguage:
      type: object
      properties:
        language:
          description: Language name.
          example: Alngith
          type: string
          format: string
    PagingData:
      type: object
      properties:
        primarylanguage:
          $ref: '#/components/schemas/PrimaryLanguagePageData'
    PagedPrimaryLanguage:
      type: object
      properties:
        primarylanguage:
          type: array
          items:
            $ref: '#/components/schemas/PrimaryLanguage'
        meta:
          $ref: '#/components/schemas/PageMetaData'
    PrimaryLanguagePageData:
      type: object
      properties:
        recordCount:
          description: The total number of primary languages returned by the underlying query.
          type: integer
          example: 4
        pageCount:
          description: The total number of pages generated by the underlying query.
          type: integer
          example: 8
        page:
          description: The page number for this page of primary languages.
          type: integer
          example: 2
        pageSize:
          description: Page size.
          type: integer
          example: 50
        prevPage:
          description: A URL to the previous page of primary languages.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/primarylanguage?page=1
        nextPage:
          description: A URL to the next page of primary languages.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/primarylanguage?page=3
    PageMetaData:
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingData'
externalDocs:
  description: API Developer Portal - Constructing API Requests
  url: https://docs.actionstep.com/api-requests/
