openapi: 3.0.3
info:
  title: Action (Matter) Bill Settings Action Bill Settings Disability Status API
  description: For retrieving Action Bill Settings. For historical reasons Matters are referred to as *actions* in this version of the API. For information of how to construct requests utilising fieldsets, sorting, paging, filters, and '*includes*', please refer to the API Developer Portal. E&OE.
  version: '1.0'
tags:
- name: Disability Status
paths:
  /disabilitystatus:
    get:
      description: Returns the list of available disability status values.
      tags:
      - Disability Status
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedDisabilityStatus'
components:
  schemas:
    PagedDisabilityStatus:
      type: object
      properties:
        disabilitystatus:
          type: array
          items:
            $ref: '#/components/schemas/DisabilityStatus'
        meta:
          $ref: '#/components/schemas/PageMetaData'
    DisabilityStatus:
      type: object
      properties:
        status:
          description: Status value.
          example: Physical
          type: string
          format: string
    PagingData:
      type: object
      properties:
        disabilitystatus:
          $ref: '#/components/schemas/DisabilityStatusPageData'
    PageMetaData:
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingData'
    DisabilityStatusPageData:
      type: object
      properties:
        recordCount:
          description: The total number of disability status values returned by the underlying query.
          type: integer
          example: 4
        pageCount:
          description: The total number of pages generated by the underlying query.
          type: integer
          example: 8
        page:
          description: The page number for this page of disability status values.
          type: integer
          example: 2
        pageSize:
          description: Page size.
          type: integer
          example: 50
        prevPage:
          description: A URL to the previous page of disability status values.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/disabilitystatus?page=1
        nextPage:
          description: A URL to the next page of disability status values.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/disabilitystatus?page=3
externalDocs:
  description: API Developer Portal - Constructing API Requests
  url: https://docs.actionstep.com/api-requests/
