openapi: 3.0.3
info:
  title: Action (Matter) Bill Settings Action Bill Settings Quick Codes API
  description: For retrieving Action Bill Settings. For historical reasons Matters are referred to as *actions* in this version of the API. For information of how to construct requests utilising fieldsets, sorting, paging, filters, and '*includes*', please refer to the API Developer Portal. E&OE.
  version: '1.0'
tags:
- name: Quick Codes
paths:
  /quickcodes:
    get:
      description: Returns the collection of all Quick Codes.
      tags:
      - Quick Codes
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedQuickCodes'
    post:
      description: Create a new Quick Code.
      tags:
      - Quick Codes
      requestBody:
        $ref: '#/components/requestBodies/CreateQuickCode'
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuickCode'
  /quickcodes/{id}:
    get:
      description: Returns a single Quick Code.
      tags:
      - Quick Codes
      parameters:
      - name: id
        in: path
        description: Unique identifier for a single Quick Code.
        required: true
        schema:
          type: integer
          format: integer
        example: 300
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuickCode'
    put:
      description: Updates a single Quick Code.
      tags:
      - Quick Codes
      parameters:
      - name: id
        in: path
        description: Unique identifier for a single Quick Code.
        required: true
        schema:
          type: integer
          format: integer
        example: 300
      requestBody:
        $ref: '#/components/requestBodies/UpdateQuickCode'
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuickCode'
components:
  schemas:
    CreateQuickCodeLinks:
      type: object
      properties:
        rate:
          description: Unique identifier for a rate associated with the quick code.
          example: 546
          type: integer
          readOnly: true
    QuickCodesPageData:
      type: object
      properties:
        recordCount:
          description: The total number of Quick Code records returned by the underlying query.
          type: integer
          example: 2487
        pageCount:
          description: The total number of pages generated by the underlying query.
          type: integer
          example: 50
        page:
          description: The page number for this page of Quick Codes.
          type: integer
          example: 2
        pageSize:
          description: Page size.
          type: integer
          example: 50
        prevPage:
          description: A URL to the previous page of Quick Codes.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/quickcodes?page=1
        nextPage:
          description: A URL to the next page of Quick Codes.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/quickcodes?page=3
    PagedQuickCodes:
      type: object
      properties:
        QuickCodes:
          type: array
          items:
            $ref: '#/components/schemas/QuickCode'
        meta:
          $ref: '#/components/schemas/PageMetaData'
    QuickCodeLinks:
      type: object
      properties:
        rate:
          description: Unique identifier for a rate associated with the quick code.
          example: 546
          type: integer
          readOnly: true
    CreateQuickCode:
      type: object
      required:
      - quickCode
      - description
      properties:
        quickCode:
          description: The value for the quick code.
          type: string
          format: string
          example: Client Communications
        description:
          description: A description for the quick code.
          type: string
          format: string
          example: For all client communications.
        useForRetainerTransfers:
          description: Indicates if the quick code is available for retainer transfers.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        useForReceipts:
          description: Indicates if the quick code is available for receipts.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        useForTasks:
          description: Indicates if the quick code is available for tasks.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        useForTimeEntry:
          description: Indicates if the quick code is available for time entry.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        useForWithdrawals:
          description: Indicates if the quick code is available for withdrawals.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        links:
          $ref: '#/components/schemas/CreateQuickCodeLinks'
    PagingData:
      type: object
      properties:
        QuickCodes:
          $ref: '#/components/schemas/QuickCodesPageData'
    QuickCode:
      type: object
      properties:
        id:
          description: Unique identifier (code) for the Quick Code.
          type: integer
          format: integer
          example: 300
          readOnly: true
        quickCode:
          description: The value for the quick code.
          type: string
          format: string
          example: Client Communications
        description:
          description: A description for the quick code.
          type: string
          format: string
          example: For all client communications.
        useForRetainerTransfers:
          description: Indicates if the quick code is available for retainer transfers.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        useForReceipts:
          description: Indicates if the quick code is available for receipts.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        useForTasks:
          description: Indicates if the quick code is available for tasks.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        useForTimeEntry:
          description: Indicates if the quick code is available for time entry.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        useForWithdrawals:
          description: Indicates if the quick code is available for withdrawals.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        links:
          $ref: '#/components/schemas/QuickCodeLinks'
    PageMetaData:
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingData'
    UpdateQuickCode:
      type: object
      properties:
        quickCode:
          description: The value for the quick code.
          type: string
          format: string
          example: Client Communications
        description:
          description: A description for the quick code.
          type: string
          format: string
          example: For all client communications.
        useForRetainerTransfers:
          description: Indicates if the quick code is available for retainer transfers.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        useForReceipts:
          description: Indicates if the quick code is available for receipts.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        useForTasks:
          description: Indicates if the quick code is available for tasks.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        useForTimeEntry:
          description: Indicates if the quick code is available for time entry.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        useForWithdrawals:
          description: Indicates if the quick code is available for withdrawals.
          type: string
          enum:
          - T
          - F
          default: T
          format: string
          example: T
        links:
          $ref: '#/components/schemas/UpdateQuickCodeLinks'
    UpdateQuickCodeLinks:
      type: object
      properties:
        rate:
          description: Unique identifier for a rate associated with the quick code.
          example: 546
          type: integer
          readOnly: true
  requestBodies:
    UpdateQuickCode:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateQuickCode'
    CreateQuickCode:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateQuickCode'
externalDocs:
  description: API Developer Portal - Constructing API Requests
  url: https://docs.actionstep.com/api-requests/
