openapi: 3.0.3

info:
  title: Participant Type Data Fields
  description: "Manages the collection of custom data fields for a participant type. For information on how to construct requests utilising fieldsets, sorting, paging, filters, and '*includes*', please refer to the API Developer Portal. E&OE."
  version: "1.0"

paths:
  '/participanttypedatafields':
    get:
      description: Returns the collection of all participant type data fields.
      tags:
        - Participant Type Data Fields
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedParticipantTypeDataFields'

    post:
      description: Create a new participant type data field.
      tags:
        - Participant Type Data Fields
      requestBody:
        $ref: '#/components/requestBodies/CreateParticipantTypeDataField'
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantTypeDataField'

  '/participanttypedatafields/{id}':
    get:
      description: Returns a single participant type data field record.
      tags:
        - Participant Type Data Fields
      parameters:
        - name: id
          in: path
          description: Unique identifier for a single participant type data field record.
          required: true
          schema:
            type: integer
            format: integer
          example: 7384
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantTypeDataField'

    put:
      description: Updates a single participant type data field record.
      tags:
        - Participant Type Data Fields
      parameters:
        - name: id
          in: path
          description: Unique identifier for a single participant type data field record.
          required: true
          schema:
            type: integer
            format: integer
          example: 7384
      requestBody:
        $ref: '#/components/requestBodies/UpdateParticipantTypeDataField'
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantTypeDataField'

    delete:
      description: Deletes a single participant type data field record.
      tags:
        - Participant Type Data Fields
      parameters:
        - name: id
          in: path
          description: Unique identifier for a single participant type data field record.
          required: true
          schema:
            type: integer
            format: integer
          example: 7384
      responses:
        '204':
          description: Success, No Content.

components:
  schemas:
    PagedParticipantTypeDataFields:
      type: object
      properties:
        participanttypedatafields:
          type: array
          items:
            $ref: '#/components/schemas/ParticipantTypeDataField'
        meta:
          $ref: '#/components/schemas/PageMetaData'

    PageMetaData:
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingData'

    PagingData:
      type: object
      properties:
        participanttypedatafields:
          $ref: '#/components/schemas/ParticipantTypeDataFieldsPageData'

    ParticipantTypeDataFieldsPageData:
      type: object
      properties:
        recordCount:
          description: The total number of participant type data field records returned by the underlying query.
          type: integer
          example: 2487
        pageCount:
          description: The total number of pages generated by the underlying query.
          type: integer
          example: 50
        page:
          description: The page number for this page of participant type data field records.
          type: integer
          example: 2
        pageSize:
          description: Page size.
          type: integer
          example: 50
        prevPage:
          description: A URL to the previous page of participant type data field records.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/participanttypedatafields?page=1
        nextPage:
          description: A URL to the next page of participant type data field records.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/participanttypedatafields?page=3

    ParticipantTypeDataField:
      type: object
      properties:
        id:
          description: Unique identifier for a single participant type data field record. 
          type: integer
          format: integer
          example: 7384
          readOnly: true
        name:
          description: Name of the participant type data field
          type: string
          format: string
          example: Colours
        dataType:
          description: The data type for the participant type data field.
          enum:
          - Boolean
          - Date
          - DateNM
          - DateTime
          - DateTimeNM
          - DropDown
          - DropDownMulti
          - Money
          - Number
          - Str255
          - Str255Protected
          - TextArea
          type: string
          format: string
          example: Str255
        label:
          description: The label for the participant type data field.
          type: string
          format: string
          example: Colour sample
        formOrder:
          description: The display order for the field when displayed on a user interface.
          type: integer
          format: string
          example: 4
        required:
          description: Indicates if a value should be provided.
          enum:
          - T
          - F
          default: F
          type: string
          format: string
        description:
          description: A descriptor for the participant type data field.
          type: string
          format: string
          example: Car colour
        synchronizeValues:
          description: When enabled (T) the field value is not unique to any specific Matter, meaning updating this field anywhere will update everywhere at the same time. When disabled (F) each Matter will have a unique value for this field.
          enum:
          - T
          - F
          default: F
          type: string
          format: string
        limitUseToMatterOnly:
          description: Enable this only if the field should not be editable on a contact record, but should be editable only on a contact linked to a matter.
          enum:
          - T
          - F
          default: F
          type: string
          format: string
        links:
          $ref: '#/components/schemas/ParticipantTypeDataFieldLinks'

    ParticipantTypeDataFieldLinks:
      type: object
      properties:
        participantType:
          description: Unique identifier for the underlying participant type.
          example: 8263
          type: integer
          format: string
          readOnly: true
        tag:
          description: Unique identifier for a tag associated with the data field.
          example: 392
          type: integer
          format: string
          readOnly: true          

    CreateParticipantTypeDataField:
      type: object
      required:
        - name
        - dataType
      properties:
        name:
          description: Name of the participant type data field
          type: string
          format: string
          example: Colours
        dataType:
          description: The data type for the participant type data field.
          enum:
          - Boolean
          - Date
          - DateNM
          - DateTime
          - DateTimeNM
          - DropDown
          - DropDownMulti
          - Money
          - Number
          - Str255
          - Str255Protected
          - TextArea
          default: Str255
          type: string
          format: string
          example: Str255
        label:
          description: The label for the participant type data field.
          type: string
          format: string
          example: Colour sample
        formOrder:
          description: The display order for the field when displayed on a user interface.
          type: integer
          format: string
          example: 4
        required:
          description: Indicates if a value should be provided.
          enum:
          - T
          - F
          default: F
          type: string
          format: string
        description:
          description: A descriptor for the participant type data field.
          type: string
          format: string
          example: Car colour
        synchronizeValues:
          description: When enabled (T) the field value is not unique to any specific Matter, meaning updating this field anywhere will update everywhere at the same time. When disabled (F) each Matter will have a unique value for this field.
          enum:
          - T
          - F
          default: F
          type: string
          format: string
        limitUseToMatterOnly:
          description: Enable this only if the field should not be editable on a contact record, but should be editable only on a contact linked to a matter.
          enum:
          - T
          - F
          default: F
          type: string
          format: string
        links:
          $ref: '#/components/schemas/CreateParticipantTypeDataFieldLinks'

    CreateParticipantTypeDataFieldLinks:
      type: object
      required:
        - participantType
      properties:
        participantType:
          description: Unique identifier for the underlying participant type.
          example: 8263
          type: integer
          format: string
        tag:
          description: Unique identifier for a tag associated with the data field.
          example: 392
          type: integer
          format: string

    UpdateParticipantTypeDataField:
      type: object
      properties:
        name:
          description: Name of the participant type data field
          type: string
          format: string
          example: Colours
        label:
          description: The label for the participant type data field.
          type: string
          format: string
          example: Colour sample
        formOrder:
          description: The display order for the field when displayed on a user interface.
          type: integer
          format: string
          example: 4
        required:
          description: Indicates if a value should be provided.
          enum:
          - T
          - F
          default: F
          type: string
          format: string
        description:
          description: A descriptor for the participant type data field.
          type: string
          format: string
          example: Car colour
        synchronizeValues:
          description: When enabled (T) the field value is not unique to any specific Matter, meaning updating this field anywhere will update everywhere at the same time. When disabled (F) each Matter will have a unique value for this field.
          enum:
          - T
          - F
          default: F
          type: string
          format: string
        limitUseToMatterOnly:
          description: Enable this only if the field should not be editable on a contact record, but should be editable only on a contact linked to a matter.
          enum:
          - T
          - F
          default: F
          type: string
          format: string
        links:
          $ref: '#/components/schemas/UpdateParticipantTypeDataFieldLinks'

    UpdateParticipantTypeDataFieldLinks:
      type: object
      required:
        - participantType
      properties:
        participantType:
          description: Unique identifier for the underlying participant type.
          example: 8263
          type: integer
          format: string
        tag:
          description: Unique identifier for a tag associated with the data field.
          example: 392
          type: integer
          format: string

  requestBodies:
    CreateParticipantTypeDataField:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateParticipantTypeDataField'

    UpdateParticipantTypeDataField:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateParticipantTypeDataField'