openapi: 3.0.3
info:
  title: Action (Matter) Bill Settings Action Bill Settings Cultural Identity API
  description: For retrieving Action Bill Settings. For historical reasons Matters are referred to as *actions* in this version of the API. For information of how to construct requests utilising fieldsets, sorting, paging, filters, and '*includes*', please refer to the API Developer Portal. E&OE.
  version: '1.0'
tags:
- name: Cultural Identity
paths:
  /culturalidentity:
    get:
      description: Returns the list of available cultural identity values.
      tags:
      - Cultural Identity
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedCulturalIdentity'
components:
  schemas:
    PagingData:
      type: object
      properties:
        culturalidentity:
          $ref: '#/components/schemas/CulturalIdentityPageData'
    CulturalIdentity:
      type: object
      properties:
        identity:
          description: Identity value.
          example: Yes, Aboriginal
          type: string
          format: string
    PageMetaData:
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingData'
    CulturalIdentityPageData:
      type: object
      properties:
        recordCount:
          description: The total number of cultural identity values returned by the underlying query.
          type: integer
          example: 4
        pageCount:
          description: The total number of pages generated by the underlying query.
          type: integer
          example: 8
        page:
          description: The page number for this page of cultural identity values.
          type: integer
          example: 2
        pageSize:
          description: Page size.
          type: integer
          example: 50
        prevPage:
          description: A URL to the previous page of cultural identity values.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/culturalidentity?page=1
        nextPage:
          description: A URL to the next page of cultural identity values.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/culturalidentity?page=3
    PagedCulturalIdentity:
      type: object
      properties:
        culturalidentity:
          type: array
          items:
            $ref: '#/components/schemas/CulturalIdentity'
        meta:
          $ref: '#/components/schemas/PageMetaData'
externalDocs:
  description: API Developer Portal - Constructing API Requests
  url: https://docs.actionstep.com/api-requests/
