openapi: 3.0.3

info:
  title: Cultural Identity 
  description: For retrieving cultural identity lookup values used by the Demograhic Information section of a participant data record. **NB:** Applicable for ANZ CLC systems only. E&OE.
  version: "1.0"

externalDocs:
  description: API Developer Portal - Constructing API Requests
  url: https://docs.actionstep.com/api-requests/

paths:
  '/culturalidentity':
    get:
      description: Returns the list of available cultural identity values.
      tags:
        - Cultural Identity
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedCulturalIdentity'

components:
  schemas:
    PagedCulturalIdentity:
      type: object
      properties:
        culturalidentity:
          type: array
          items:
            $ref: '#/components/schemas/CulturalIdentity'
        meta:
          $ref: '#/components/schemas/PageMetaData'

    PageMetaData:
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingData'

    PagingData:
      type: object
      properties:
        culturalidentity:
          $ref: '#/components/schemas/CulturalIdentityPageData'

    CulturalIdentityPageData:
      type: object
      properties:
        recordCount:
          description: The total number of cultural identity values returned by the underlying query.
          type: integer
          example: 4
        pageCount:
          description: The total number of pages generated by the underlying query.
          type: integer
          example: 8
        page:
          description: The page number for this page of cultural identity values.
          type: integer
          example: 2
        pageSize:
          description: Page size.
          type: integer
          example: 50
        prevPage:
          description: A URL to the previous page of cultural identity values.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/culturalidentity?page=1
        nextPage:
          description: A URL to the next page of cultural identity values.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/culturalidentity?page=3

    CulturalIdentity:
      type: object
      properties:
        identity:
          description: Identity value.
          example: Yes, Aboriginal
          type: string
          format: string