openapi: 3.2.0
info:
  title: Contact Relationships API
  description: Actionstep provide a feature to manage relationships between contacts.
  version: '1.0'
tags:
- name: Contact Relationships
paths:
  /contactrelationships:
    get:
      description: Returns the collection of all contact relationships.
      tags:
      - Contact Relationships
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedContactRelationships'
      summary: Get contactrelationships
      x-summary-source: derived
      operationId: getContactrelationships
      x-operation-id-source: derived
    post:
      description: Create a new contact relationship.
      tags:
      - Contact Relationships
      requestBody:
        $ref: '#/components/requestBodies/CreateContactRelationship'
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateContactRelationship'
      summary: Create contactrelationships
      x-summary-source: derived
      operationId: postContactrelationships
      x-operation-id-source: derived
  /contactrelationships/{id}:
    get:
      description: Returns a single contact relationship record.
      tags:
      - Contact Relationships
      parameters:
      - name: id
        in: path
        description: Unique identifier for a single contact relationship record. The identifier is composed from the relationship, fromContact, and toContact properties separated by "--".
        required: true
        schema:
          type: string
          format: string
        example: Father-41854-845258
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactRelationship'
      summary: Get contactrelationships by id
      x-summary-source: derived
      operationId: getContactrelationshipsById
      x-operation-id-source: derived
    delete:
      description: Deletes a single contact relationship record.
      tags:
      - Contact Relationships
      parameters:
      - name: id
        in: path
        description: Unique identifier for a single contact relationship record. The identifier is composed from the relationship, fromContact, and toContact properties separated by "--".
        required: true
        schema:
          type: string
          format: string
        example: Father-41854-845258
      responses:
        '204':
          description: Success, No Content.
      summary: Delete contactrelationships by id
      x-summary-source: derived
      operationId: deleteContactrelationshipsById
      x-operation-id-source: derived
components:
  schemas:
    CreateContactRelationship:
      type: object
      required:
      - relationship
      properties:
        relationship:
          description: The relationship name between the two contacts.
          type: string
          format: string
          example: Father
        links:
          $ref: '#/components/schemas/CreateContactRelationshipLinks'
    PagingData:
      type: object
      properties:
        contactrelationships:
          $ref: '#/components/schemas/ContactRelationshipsPageData'
    ContactRelationshipsPageData:
      type: object
      properties:
        recordCount:
          description: The total number of contact relationship records returned by the underlying query.
          type: integer
          example: 2487
        pageCount:
          description: The total number of pages generated by the underlying query.
          type: integer
          example: 50
        page:
          description: The page number for this page of contact relationship records.
          type: integer
          example: 2
        pageSize:
          description: Page size.
          type: integer
          example: 50
        prevPage:
          description: A URL to the previous page of contact relationship records.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/contactrelationships?page=1
        nextPage:
          description: A URL to the next page of contact relationship records.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/contactrelationships?page=3
    PageMetaData:
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingData'
    PagedContactRelationships:
      type: object
      properties:
        contactrelationships:
          type: array
          items:
            $ref: '#/components/schemas/ContactRelationship'
        meta:
          $ref: '#/components/schemas/PageMetaData'
    ContactRelationship:
      type: object
      properties:
        id:
          description: Unique identifier for a single contact relationship record. The identifier is composed from the relationship, fromContact, and toContact properties separated by "--".
          type: string
          format: string
          example: Father-41854-845258
          readOnly: true
        relationship:
          description: The relationship name between the two contacts.
          type: string
          format: string
          example: Father
        links:
          $ref: '#/components/schemas/ContactRelationshipLinks'
    CreateContactRelationshipLinks:
      type: object
      required:
      - fromContact
      - toContact
      properties:
        fromContact:
          description: Unique identifier for the contact from which a relationship is to be established.
          example: 41854
          type: integer
        toContact:
          description: Unique identifier for the contact to which a relationship is to be established.
          example: 321845
          type: integer
    ContactRelationshipLinks:
      type: object
      properties:
        fromContact:
          description: Unique identifier for the contact from which a relationship is established.
          example: 41854
          type: integer
          readOnly: true
        toContact:
          description: Unique identifier for the contact to which a relationship is established.
          example: 321845
          type: integer
          readOnly: true
  requestBodies:
    CreateContactRelationship:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateContactRelationship'
externalDocs:
  description: Tutorial - Working with Contact Relationships
  url: https://docs.actionstep.com/tutorial-contact-relationships/
