openapi: 3.0.3

info:
  title: Gender Types
  description: "For managing custom gender types. E&OE."
  version: "1.0"

paths:
  '/gendertypes':
    get:
      description: Returns a list of custom gender types.
      tags:
        - Gender Types
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedGenderTypes'

    post:
      description: Create a new custom gender type. 
      tags:
        - Gender Types
      requestBody:
        $ref: '#/components/requestBodies/CreateGenderType'
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenderType'

  '/gendertypes/{genderTypeName}': 
    get:
      description: Returns a single custom gender type.
      tags:
        - Gender Types
      parameters:
        - name: genderTypeName
          in: path
          description: Name of the custom gender type.
          required: true
          schema:
            type: string
          example: Transgender
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenderType'

    put:
      description: Update a single custom gender type.
      tags:
        - Gender Types
      parameters:
        - name: genderTypeName
          in: path
          description: Name of the custom gender type.
          required: true
          schema:
            type: string
          example: Transgender
      requestBody:
        $ref: '#/components/requestBodies/UpdateGenderType'
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenderType'
  
    delete:
      description: Delete a custom gender type. Please note - you cannot delete a custom gender type if it is already assigned to an existing participant record.
      tags:
        - Gender Types
      parameters:
        - name: genderTypeName
          in: path
          description: Name of the custom gender type.
          required: true
          schema:
            type: string
          example: Transgender
      responses:
        '204':
          description: Success, No content.

components:
  schemas:
    PagedGenderTypes:
      type: object
      properties:
        gendertypes:
          type: array
          items:
            $ref: '#/components/schemas/GenderType'
        meta:
          $ref: '#/components/schemas/PageMetaData'

    PageMetaData:
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingData'

    PagingData:
      type: object
      properties:
        gendertypes:
          $ref: '#/components/schemas/GenderTypesPageData'

    GenderTypesPageData:
      type: object
      properties:
        recordCount:
          description: The total number of custom gender types returned by the underlying query.
          type: integer
          example: 4
        pageCount:
          description: The total number of pages generated by the underlying query.
          type: integer
          example: 8
        page:
          description: The page number for this page of custom gender types.
          type: integer
          example: 2
        pageSize:
          description: Page size.
          type: integer
          example: 50
        prevPage:
          description: A URL to the previous page of custom gender types.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/gendertypes?page=1
        nextPage:
          description: A URL to the next page of custom gender types.
          type: string
          example: https://ap-southeast-2.actionstep.com/api/rest/gendertypes?page=3

    GenderType:
      type: object
      properties:
        genderTypeName:
          description: Name of the custom gender type.
          example: Transgender
          type: string
        pronounType:
          description: One of 'Male', 'Female', 'Neutral', or 'Company'.
          enum:
          - Male
          - Female
          - Neutral
          - Company
          example: Neutral
          type: string

    CreateGenderType:
      type: object
      required: 
        - genderTypeName
        - pronounType
      properties:
        genderTypeName:
          description: Name of the custom gender type.
          example: Transgender
          type: string
        pronounType:
          description: One of 'Male', 'Female', 'Neutral', or 'Company'.
          enum:
          - Male
          - Female
          - Neutral
          - Company
          example: Neutral
          type: string

    UpdateGenderType:
      type: object
      required: 
        - pronounType
      properties:
        pronounType:
          description: One of 'Male', 'Female', 'Neutral', or 'Company'.
          enum:
          - Male
          - Female
          - Neutral
          - Company
          example: Neutral
          type: string

  requestBodies:
    CreateGenderType:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateGenderType'
            
    UpdateGenderType:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateGenderType'